### PR TITLE
check if project pub linker exists first

### LINKED ISSUE #153: project pub linker table causes tests to fail locally
```

1) Tests\EUtilsBioProjectRepositoryTest::testProjectFromXML
PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "project_pub_c1"
DETAIL:  Key (project_id, pub_id)=(373, 206) already exists.

```

Looks like we need to check to make sure the project/pub aren't already linked before inserting in this table.

I think if we use the chado API instead we wont have to worry about that.

### PR DESCRIPTION
**Pull request by bradfordcondon**
resolve #153

### CODE REVIEW

File: tests/EUtilsBioProjectRepositoryTest.php [hunk 1]
```diff
@@ -41,6 +41,7 @@ public function testCreatingBioProject() {
 
   /**
    * @group bioproject
+   * @group failing
```
Comment (bradfordcondon) [inline tests/EUtilsBioProjectRepositoryTest.php]:
```suggestion
```
